import os
import sys
import time
import logging
import webbrowser
from datetime import datetime

if getattr(sys, 'frozen', False):
    BASE_DIR = os.path.dirname(sys.executable)
else:
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

CONFIG_FILE = os.path.join(BASE_DIR, "autodemo.txt")                    # файл настроек программы
CFG_DIR = os.path.join(BASE_DIR, "nmrih", "cfg")                        # директория конфигов
TARGET_CFG = os.path.join(CFG_DIR, "auto_record_timestamp.cfg")         # конфиг с алиасом, который используется при активации бинда
AUTOEXEC_CFG = os.path.join(CFG_DIR, "autoexec.cfg")                    # путь к autoexec.cfg

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

DEFAULT_FORMAT = "%d-%m-%Y_%H-%M"
DEFAULT_INTERVAL = 10
DEFAULT_BINDKEY = "backspace"

def initConfig():
    """читает autodemo.txt"""
    # ПЕРЕМЕННЫЕ ПАРАМЕТРОВ
    format = DEFAULT_FORMAT
    interval = DEFAULT_INTERVAL
    bindKey = DEFAULT_BINDKEY

    if not os.path.exists(CONFIG_FILE):                                 # если autodemo.txt не найден
        try:
            with open(CONFIG_FILE, "w", encoding="utf-8") as f:         # создается свой со следующим наполнением
                f.write("# === autodemo settings ===\n")
                f.write("# FORMAT: шаблон названия демо:\n")
                f.write("# %d - день, %m - месяц, %Y - год, %H - часы (24ч), %M - минуты, %S - секунды\n")
                f.write("# INTERVAL: задержка перезаписывания алиаса (секунды)\n")
                f.write("# BIND_KEY: клавиша в игре для записи\n")
                f.write(f"FORMAT={DEFAULT_FORMAT}\n")
                f.write(f"INTERVAL={DEFAULT_INTERVAL}\n")
                f.write(f"BIND_KEY={DEFAULT_BINDKEY}\n")
            logging.info("Создан новый файл конфигурации autodemo.txt")
        except Exception as e:
            logging.error(f"Ошибка при создании autodemo.txt: {e}")
    else:                                                               # иначе (файл все таки есть)
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):        # если строчка пустая или начинается с #
                        continue                                # продолжается
                    if "=" in line:                             # если в строке есть =
                        key, val = line.split("=", 1)           # составляется список из пары ПАРАМЕТР-ЗНАЧЕНИЕ, разделенных "=" и распаковывается в переменные
                        key = key.strip().upper()               # удаляются пробелы и переводится в верхний регистр
                        val = val.strip()                       # удаляются пробелы 
                        if key == "FORMAT":                     # если параметр является FORMAT
                            format = val                        # формат равняется его значению
                        elif key == "INTERVAL":                 # иначе если параметр равняется INTERVAL
                            try:
                                interval = max(1, int(val))     # интервал высчитывается как наибольшее из 1 и значения
                            except ValueError:                  # на всякий случай, если произойдет ошибка - все пропускается и используется стандартное значение
                                pass
                        elif key == "BIND_KEY":                 # иначе если параметр равняется BIND_KEY
                            bindKey = val.lower()               # бинд равняется его значению
        except Exception as e:
            logging.error(f"Ошибка при чтении autodemo.txt: {e}")

    return format, interval, bindKey                            # возвращаются формат, интервал и бинд, распаковываясь в переменные при вызове


def updateBind(bindKey):
    """обновляет бинд в autoexec.cfg"""
    bindCommand = f'bind "{bindKey}" "exec auto_record_timestamp; start_demo_timestamped"\n'

    try:
        # ЕСЛИ НЕТ ПАПКИ CFG 
        if not os.path.exists(CFG_DIR):
            os.makedirs(CFG_DIR, exist_ok=True)

        # ЕСЛИ НЕТ AUTOEXEC.CFG
        if not os.path.exists(AUTOEXEC_CFG):
            with open(AUTOEXEC_CFG, "w", encoding="utf-8") as f:
                f.write("// Auto-generated by autodemo NMRIH\n")
                f.write(bindCommand)
            logging.info(f"Создан autoexec.cfg с биндом на клавишу [{bindKey}]")
            return

        # ОТКРЫВАЕТ ФАЙЛ AUTOEXEC.CFG
        with open(AUTOEXEC_CFG, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines() # собирает список строк файла

        bindExists = False      # есть ли бинд в файле
        updated = False         # был ли обновлен файл
        newLines = []           # результирующий список строчек файла (измененнная копия)

        for line in lines:                                          # перебирает каждую строчку файла
            if "start_demo_timestamped" in line:                    # если найдена строчка с командой
                if line.strip() == bindCommand.strip():             # если строчка команды из файла равна команде
                    bindExists = True                               # бинд в файле есть
                    newLines.append(line)                           # строчка добавляется в список
                                                                        # --- файл не перезаписывается, ибо бинд в файле совпал
                else:                                               # иначе 
                    newLines.append(bindCommand)                    # в список добавляется стандартная команда
                    updated = True                                  # конфиг обновлен
                    bindExists = True                               # бинд в файле есть
            else:                                                   # иначе 
                newLines.append(line)                               # строчка добавляется в список
                                                                        # --- файл перезаписывается, ибо бинд был другим

        if not bindExists:                                          # если бинда нет в файле
            if newLines and not newLines[-1].endswith("\n"):        # если в списке есть что то и нет ли в конце перехода на новую строку
                newLines.append("\n")                               # добавляется переход на новую строку в список
            newLines.append(bindCommand)                            # добавляется команда
            updated = True                                          # конфиг обновлен
                                                                        # --- файл перезаписывается, ибо команды вообще не было 

        if updated:                                                 # если конфиг был обновлен
            with open(AUTOEXEC_CFG, "w", encoding="utf-8") as f:    # открывается autoexec.cfg
                f.writelines(newLines)                              # записывается весь список с командой (измененная копия файла полностью заменяет старую версию)
            logging.info(f"Бинд в autoexec.cfg обновлен на клавишу [{bindKey}]")

    except Exception as e:
        logging.error(f"Ошибка при работе с autoexec.cfg: {e}")


def writeCommand(dateFormat):
    """записывает в auto_record_timestamp.cfg актуальный алиас"""
    try:
        timestamp = datetime.now().strftime(dateFormat)                         # дата и время в указанном формате
        cfgContent = f'alias start_demo_timestamped "record {timestamp}"\n'     # собранный алиас для конфига

        with open(TARGET_CFG, "w", encoding="utf-8") as f:
            f.write(cfgContent)                                                 # запись алиаса в конфиг

        logging.info(f"Конфиг обновлен: alias start_demo_timestamped \"record {timestamp}\"")
    except Exception as e:
        logging.error(f"Ошибка при записи {TARGET_CFG}: {e}")


def main():
    logging.info("=== AutoDemo NMRIH by Sh!kei v1.1 ===")
    logging.info(f"Рабочая директория: {BASE_DIR}")

    # первичное чтение конфига и автодобавление бинда в autoexec.cfg
    format, interval, bindKey = initConfig()
    updateBind(bindKey)

    # запуск игры в Steam
    try:
        webbrowser.open("steam://rungameid/224260")
        logging.info("Запуск игры (rungameid/224260)")
    except Exception as e:
        logging.error(f"Не удалось запустить игру: {e}")

    # бесконечный цикл синхронизации
    lastKey = bindKey
    while True:
        format, interval, bindKey = initConfig()
        if bindKey != lastKey:
            updateBind(bindKey)
            lastKey = bindKey

        writeCommand(format)
        time.sleep(interval)


if __name__ == "__main__":
    main()